/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/onboarding/petani": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Daftar sebagai petani (A-01, A-02)
         * @description Sign up on the supply side.
         *
         *     Returns an access token -- copy it into the **Authorize** button at the
         *     top of this page to use it for the rest of the flow.
         */
        post: operations["daftar_petani_onboarding_petani_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/pembeli": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar seluruh pembeli terdaftar (bantuan demo)
         * @description Convenience listing so a demo can see who exists without a DB client.
         *
         *     Not part of any PRD requirement.
         */
        get: operations["daftar_pembeli_terdaftar_onboarding_pembeli_get"];
        put?: never;
        /** Daftar sebagai pembeli (A-01, A-03) */
        post: operations["daftar_pembeli_onboarding_pembeli_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil saya, termasuk ringkasan reputasi (A-04) */
        get: operations["profil_saya_onboarding_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/saya/lokasi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Perbarui lokasi utama (A-02) */
        patch: operations["perbarui_lokasi_onboarding_saya_lokasi_patch"];
        trace?: never;
    };
    "/onboarding/pengguna/{id_pengguna}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lihat profil pihak lain (F-07: reputasi terlihat sebelum kontak) */
        get: operations["profil_pengguna_onboarding_pengguna__id_pengguna__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/klasifikasi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Klasifikasi otomatis dari foto (B-01 … B-06, B-08)
         * @description Upload photos and get back a condition label.
         *
         *     ⚠️ **Hasil saat ini berasal dari pengklasifikasi tiruan**, bukan model YOLO
         *     terlatih — lihat `sumber_placeholder` pada respons. Bentuk respons sudah
         *     final dan tidak berubah saat model asli dipasang.
         *
         *     Hasil bervariasi antar foto tapi konsisten untuk foto yang sama, sehingga
         *     demo dapat diulang. Sekitar 1 dari 8 foto sengaja menghasilkan keyakinan
         *     rendah agar jalur konfirmasi manual (B-06) dapat diperagakan.
         */
        post: operations["klasifikasi_otomatis_klasifikasi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/klasifikasi/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Klasifikasi manual / fallback (B-07)
         * @description Declare the condition yourself, without a model in the loop.
         *
         *     The result is tagged `manual_dilaporkan_sendiri` and stays visually
         *     distinguishable to buyers wherever it appears (PRD F-03).
         */
        post: operations["klasifikasi_manual_klasifikasi_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/klasifikasi/{id_klasifikasi}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lihat hasil klasifikasi */
        get: operations["ambil_klasifikasi_klasifikasi__id_klasifikasi__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/penawaran": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar penawaran */
        get: operations["daftar_penawaran_penawaran_get"];
        put?: never;
        /**
         * Publikasikan penawaran panen (§10.1 langkah 5)
         * @description Publish harvest so buyers can find it.
         *
         *     Creating an offer immediately runs it against every active buyer demand
         *     (PRD E-02) and notifies whoever matches (E-03). `jumlah_permintaan_cocok`
         *     in the response tells you how many buyers were alerted.
         */
        post: operations["buat_penawaran_penawaran_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/penawaran/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Penawaran milik saya */
        get: operations["penawaran_saya_penawaran_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/penawaran/{id_penawaran}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail penawaran */
        get: operations["detail_penawaran_penawaran__id_penawaran__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/penawaran/{id_penawaran}/tersalurkan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tandai penawaran sudah tersalurkan */
        post: operations["tandai_tersalurkan_penawaran__id_penawaran__tersalurkan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permintaan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pasang permintaan pembeli (E-01)
         * @description Post standing demand -- the reverse flow (PRD §10.2).
         *
         *     Farmers publishing matching supply after this will trigger a notification
         *     to you, without you searching.
         */
        post: operations["buat_permintaan_permintaan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permintaan/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Permintaan milik saya */
        get: operations["permintaan_saya_permintaan_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permintaan/{id_permintaan}/tutup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tutup permintaan lebih awal (E-04) */
        post: operations["tutup_permintaan_permintaan__id_permintaan__tutup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/penawaran/{id_penawaran}/rekomendasi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 2-3 opsi penyaluran untuk sebuah penawaran (C-01 … C-05)
         * @description Disposal/sale options for a published offer.
         *
         *     Every option carries `id_aturan` -- the row in `config/rule_base.yaml`
         *     that produced it (PRD C-01 acceptance, NF-06). Options are also marked
         *     with whether a matching buyer actually exists nearby (C-03).
         */
        get: operations["rekomendasi_penawaran__id_penawaran__rekomendasi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/basis-aturan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Isi basis pengetahuan saat ini (C-04)
         * @description The whole rule table as currently loaded.
         *
         *     Exposed so the team can confirm an edit to `config/rule_base.yaml`
         *     actually took effect, without database access or a redeploy.
         *
         *     ⚠️ Isi tabel ini masih berasal dari studi literatur dan belum divalidasi
         *     lewat wawancara pembeli (PRD §15).
         */
        get: operations["basis_aturan_basis_aturan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/penawaran/{id_penawaran}/pembeli": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pembeli terdekat yang cocok, terurut (D-01 … D-06)
         * @description Forward flow: the farmer sees who can take this harvest.
         *
         *     Ranked by condition relevance, then proximity (PRD D-03). Every row
         *     carries `alasan` -- the component scores and weights behind its position
         *     (NF-06). An empty result explains which filter removed each candidate
         *     rather than returning a bare empty list.
         *
         *     Distance filters and ranks. It is never converted into a cost -- transport
         *     economics are out of scope (PRD §3.2).
         */
        get: operations["cari_pembeli_penawaran__id_penawaran__pembeli_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/penawaran/{id_penawaran}/kecocokan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kecocokan yang sudah tercatat untuk penawaran ini */
        get: operations["kecocokan_penawaran_penawaran__id_penawaran__kecocokan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kecocokan/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pasokan cocok yang masuk ke permintaan saya (E-02, E-03)
         * @description Reverse flow: what has matched the demands this buyer posted.
         *
         *     These rows are created automatically when a farmer publishes matching
         *     supply -- the buyer does not search for them.
         */
        get: operations["kecocokan_saya_kecocokan_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transaksi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Catat kesepakatan transaksi
         * @description Record an agreed deal.
         *
         *     Terra records that an agreement happened; it does not process payment or
         *     hold funds (out of scope, PRD §3.2). This record is what both reputation
         *     directions and the impact dashboard are computed from.
         */
        post: operations["buat_transaksi_transaksi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transaksi/{id_transaksi}/selesai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Selesaikan transaksi dan beri penilaian (§10.1 langkah 8) */
        post: operations["selesaikan_transaksi_transaksi__id_transaksi__selesai_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transaksi/{id_transaksi}/batal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batalkan transaksi yang sudah disepakati (F-06)
         * @description Cancel after agreement -- recorded against whoever cancelled.
         *
         *     This is the buyer-side accountability half of PRD F-06: the interview
         *     finding was that farmers absorb 100% of the loss when a verbally-agreed
         *     order is pulled, with no reputational consequence for the buyer.
         */
        post: operations["batalkan_transaksi_transaksi__id_transaksi__batal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transaksi/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Riwayat transaksi saya */
        get: operations["transaksi_saya_transaksi_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/laporan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Laporkan ketidaksesuaian kondisi (F-04)
         * @description File a post-transaction mismatch report with comparison photos.
         */
        post: operations["buat_laporan_laporan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/laporan/{id_laporan}/tinjau": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tinjau laporan: konfirmasi atau tolak (F-05)
         * @description Confirm or reject a report; only confirmed ones move a score.
         *
         *     ⚠️ **Belum ada peran moderator.** Endpoint ini terbuka untuk semua
         *     pengguna terautentikasi, yang jelas tidak memadai di luar MVP. Autentikasi
         *     tingkat produksi berada di luar lingkup saat ini (context.md) -- siapa pun
         *     yang menambahkan peran pengguna sebaiknya menutup endpoint ini lebih dulu.
         */
        post: operations["tinjau_laporan_laporan__id_laporan__tinjau_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/laporan/terhadap/{id_pengguna}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Laporan terhadap seorang pengguna */
        get: operations["laporan_terhadap_laporan_terhadap__id_pengguna__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reputasi/{id_pengguna}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reputasi dua arah seorang pengguna (F-05, F-06, F-07)
         * @description Reputation derived from logged events, not from free-text reviews.
         *
         *     `ringkasan_teks` states what the numbers are made of, so the counterparty
         *     sees the basis and not just a figure (PRD F-06 acceptance).
         */
        get: operations["reputasi_reputasi__id_pengguna__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifikasi/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Notifikasi saya, yang mendesak lebih dulu (H-01, H-02)
         * @description Notifications for the signed-in user.
         *
         *     ⚠️ **Pengiriman push masih placeholder.** Notifikasi disusun, diberi
         *     prioritas dan disimpan sungguhan, tapi tidak dikirim ke perangkat -- lihat
         *     `status_kirim` dan `modules/notifications/pengirim.py`. Endpoint ini
         *     adalah cara memverifikasi bahwa pencocokan balik (E-03) benar-benar
         *     memicu notifikasi ke pembeli yang tepat.
         */
        get: operations["notifikasi_saya_notifikasi_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifikasi/{id_notifikasi}/dibaca": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tandai notifikasi sudah dibaca */
        post: operations["tandai_dibaca_notifikasi__id_notifikasi__dibaca_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/penawaran/{id_penawaran}/kartu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kartu penawaran siap dibagikan (G-01)
         * @description Card content for the native share sheet.
         *
         *     Returns data, not a rendered page: the React Native app draws the card and
         *     hands it to the OS share sheet (G-02). There is no web surface in this
         *     product, so the §6.7 acceptance criterion about a WhatsApp *link preview*
         *     is not met -- that would require a public HTML page with OG tags.
         *
         *     `lokasi_umum` is deliberately coarse. Cards land in open groups, and the
         *     farmer's exact pin should not travel with them.
         */
        get: operations["kartu_penawaran_penawaran__id_penawaran__kartu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/penawaran/{id_penawaran}/kartu/dibagikan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Catat bahwa kartu benar-benar dibagikan (analitik §12)
         * @description Called by the app after the share sheet closes.
         *
         *     Feeds the `card_shared` metric -- how much the external-channel path is
         *     actually used, which is one of the proposal's core behavioural claims.
         */
        post: operations["catat_berbagi_penawaran__id_penawaran__kartu_dibagikan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/komunitas/papan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Papan komunitas regional (G-03)
         * @description Active listings and discussion for an area.
         *
         *     A passive information surface. No shipment pooling is built on top of it,
         *     by design (PRD G-04, §3.2).
         */
        get: operations["papan_komunitas_papan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/komunitas/pos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tulis pos di papan komunitas (G-03) */
        post: operations["buat_pos_komunitas_pos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dampak/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dampak kumulatif saya (I-01, I-02)
         * @description Cumulative value recovered, volume diverted, successful connections.
         *
         *     Aggregated from the signed-in user's own transaction history (I-02) --
         *     no platform-wide figures, and nothing extrapolated.
         */
        get: operations["dampak_saya_dampak_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Info layanan */
        get: operations["akar__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cek kesehatan */
        get: operations["kesehatan_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Aturan
         * @description One row of the knowledge base.
         */
        Aturan: {
            /** Id */
            id: string;
            komoditas: components["schemas"]["Komoditas"];
            /** Jenis Kondisi */
            jenis_kondisi: components["schemas"]["KondisiKode"][];
            /** Keparahan */
            keparahan: components["schemas"]["TingkatKeparahan"][];
            /** Catatan Aturan */
            catatan_aturan?: string | null;
            /** Opsi */
            opsi: components["schemas"]["Opsi"][];
        };
        /** BasisPengetahuan */
        BasisPengetahuan: {
            /** Versi */
            versi: number;
            /** Aturan */
            aturan: components["schemas"]["Aturan"][];
        };
        /** BatalkanTransaksiRequest */
        BatalkanTransaksiRequest: {
            /** Alasan */
            alasan?: string | null;
        };
        /** Body_klasifikasi_otomatis_klasifikasi_post */
        Body_klasifikasi_otomatis_klasifikasi_post: {
            /** @description PRD B-03 */
            komoditas: components["schemas"]["Komoditas"];
            /** @description PRD B-04 */
            pemicu: components["schemas"]["Pemicu"];
            /**
             * Foto
             * @description 1-3 foto (PRD B-01)
             */
            foto: string[];
            /**
             * Waktu Ambil
             * @description Waktu tangkap ISO-8601 dari kamera aplikasi (B-02).
             */
            waktu_ambil?: string | null;
            /**
             * Latitude
             * @description Koordinat tangkap foto (B-02, F-02).
             */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
        };
        /**
         * BuatLaporanRequest
         * @description PRD F-04: post-transaction mismatch report with comparison photo.
         */
        BuatLaporanRequest: {
            /** Id Transaksi */
            id_transaksi: string;
            /**
             * Kondisi Ditemukan
             * @description Kondisi sebenarnya yang ditemukan saat barang diterima.
             */
            kondisi_ditemukan: components["schemas"]["KondisiKode"][];
            /** Catatan */
            catatan?: string | null;
            /**
             * Foto Pembanding
             * @description Foto pembanding saat barang diterima.
             */
            foto_pembanding?: components["schemas"]["Citra"][];
        };
        /**
         * BuatPenawaranRequest
         * @description Publish harvest for matching.
         *
         *     Two ways in, matching PRD §10.1:
         *
         *     * **From a classification** -- pass `id_klasifikasi` and the commodity and
         *       condition fields are taken from that run.
         *     * **Self-reported** -- omit `id_klasifikasi` and supply `komoditas`,
         *       `pemicu`, `jenis_kondisi` and `tingkat_keparahan` yourself. The offer is
         *       tagged `manual_dilaporkan_sendiri` (PRD B-07, F-03).
         */
        BuatPenawaranRequest: {
            /**
             * Id Klasifikasi
             * @example kls_1a2b3c4d5e
             */
            id_klasifikasi?: string | null;
            komoditas?: components["schemas"]["Komoditas"] | null;
            pemicu?: components["schemas"]["Pemicu"] | null;
            /** Jenis Kondisi */
            jenis_kondisi?: components["schemas"]["KondisiKode"][] | null;
            tingkat_keparahan?: components["schemas"]["TingkatKeparahan"] | null;
            /** Citra */
            citra?: components["schemas"]["Citra"][];
            /**
             * Volume
             * @description kg
             * @example 120
             */
            volume: number;
            /**
             * Lama Sejak Panen
             * @example 2
             */
            lama_sejak_panen?: number | null;
            kondisi_penyimpanan?: components["schemas"]["KondisiPenyimpanan"] | null;
            /** @description Kosongkan untuk memakai lokasi terdaftar petani (A-02). */
            koordinat?: components["schemas"]["Koordinat"] | null;
        };
        /**
         * BuatPermintaanRequest
         * @description PRD E-01: buyer posts standing demand (the reverse flow).
         */
        BuatPermintaanRequest: {
            /**
             * Komoditas Dicari
             * @example [
             *       "tomat"
             *     ]
             */
            komoditas_dicari: components["schemas"]["Komoditas"][];
            /**
             * Kondisi Diterima
             * @example [
             *       "K0",
             *       "K1",
             *       "K2"
             *     ]
             */
            kondisi_diterima: components["schemas"]["KondisiKode"][];
            /** @description Batas atas keparahan yang masih diterima. */
            keparahan_maksimal: components["schemas"]["TingkatKeparahan"];
            /**
             * Volume Minimum
             * @description kg. Penawaran di bawah ini tidak ditampilkan (D-04).
             * @default 0
             */
            volume_minimum: number;
            /**
             * Volume Dibutuhkan
             * @description kg
             * @example 500
             */
            volume_dibutuhkan: number;
            /**
             * Radius Maksimal
             * @description km (D-02)
             * @default 50
             */
            radius_maksimal: number;
            /** @description Harga yang ditawarkan pembeli per kg PRODUK. Bukan ongkos angkut. */
            rentang_harga?: components["schemas"]["RentangHarga"];
            /** @description Kosongkan untuk memakai lokasi terdaftar pembeli. */
            koordinat?: components["schemas"]["Koordinat"] | null;
            /**
             * Berlaku Hingga
             * @description Kedaluwarsa otomatis (E-04).
             */
            berlaku_hingga?: string | null;
        };
        /**
         * BuatPosRequest
         * @description PRD G-03: a free-text post on the regional board.
         */
        BuatPosRequest: {
            /**
             * Wilayah
             * @example Lembang, Bandung Barat
             */
            wilayah: string;
            /** Isi */
            isi: string;
        };
        /**
         * BuatTransaksiRequest
         * @description Record that a deal was agreed.
         *
         *     Terra does not process payment or hold escrow (PRD §3.2) -- this is a
         *     record that two parties agreed, which is what both reputation directions
         *     and the impact dashboard are computed from.
         */
        BuatTransaksiRequest: {
            /** Id Penawaran */
            id_penawaran: string;
            /** Id Pembeli */
            id_pembeli: string;
            /**
             * Volume
             * @description kg yang disepakati
             */
            volume: number;
            /**
             * Nilai Total
             * @description Nilai produk yang disepakati, Rupiah. Tanpa komponen ongkos angkut.
             */
            nilai_total: number;
        };
        /**
         * Citra
         * @description One photo attached to an offer (PRD §8 `citra`, B-02).
         *
         *     `waktu_ambil` and the capture coordinates come from the device at capture
         *     time. PRD F-01 requires in-app capture rather than gallery upload; the
         *     backend enforces the *presence* of this metadata, which is as far as
         *     server-side verification can go.
         */
        Citra: {
            /** Url */
            url: string;
            /** Waktu Ambil */
            waktu_ambil: string;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
        };
        /**
         * DaftarPembeliRequest
         * @description PRD A-01 + A-03.
         */
        DaftarPembeliRequest: {
            /**
             * Nama
             * @example Bu Rina
             */
            nama: string;
            jenis_usaha: components["schemas"]["JenisUsaha"];
            /**
             * Nama Usaha
             * @example CV Saus Lembang
             */
            nama_usaha?: string | null;
            koordinat: components["schemas"]["Koordinat"];
            /**
             * Alamat Umum
             * @example Cimahi
             */
            alamat_umum?: string | null;
            /**
             * Nomor Whatsapp
             * @example 6281234567891
             */
            nomor_whatsapp?: string | null;
        };
        /**
         * DaftarPetaniRequest
         * @description PRD A-01 + A-02. Deliberately few fields (NF-02: max 3 steps).
         */
        DaftarPetaniRequest: {
            /**
             * Nama
             * @example Pak Dedi
             */
            nama: string;
            koordinat: components["schemas"]["Koordinat"];
            /**
             * Komoditas Utama
             * @example [
             *       "tomat",
             *       "wortel"
             *     ]
             */
            komoditas_utama?: components["schemas"]["Komoditas"][];
            /**
             * Alamat Umum
             * @description Lokasi umum yang ditampilkan ke pihak lain, bukan titik persis.
             * @example Lembang, Bandung Barat
             */
            alamat_umum?: string | null;
            /**
             * Nomor Whatsapp
             * @example 6281234567890
             */
            nomor_whatsapp?: string | null;
        };
        /**
         * DampakResponse
         * @description PRD I-01: cumulative impact for one user.
         */
        DampakResponse: {
            /** Id Pengguna */
            id_pengguna: string;
            /**
             * Nilai Terpulihkan
             * @description Total nilai produk yang berhasil disalurkan, Rupiah. Nilai kotor produk -- tanpa potongan ongkos angkut, yang memang tidak dimodelkan (PRD §3.2).
             */
            nilai_terpulihkan: number;
            /**
             * Volume Dialihkan Kg
             * @description Volume yang tersalurkan alih-alih terbuang.
             */
            volume_dialihkan_kg: number;
            /**
             * Jumlah Koneksi Berhasil
             * @description Transaksi berstatus selesai.
             */
            jumlah_koneksi_berhasil: number;
            /**
             * Jumlah Penawaran Dibuat
             * @default 0
             */
            jumlah_penawaran_dibuat: number;
            /**
             * Jumlah Penawaran Tersalurkan
             * @default 0
             */
            jumlah_penawaran_tersalurkan: number;
            /**
             * Tingkat Penyaluran
             * @description Proporsi penawaran yang berakhir tersalurkan.
             */
            tingkat_penyaluran?: number | null;
            /**
             * Transaksi Dibatalkan
             * @default 0
             */
            transaksi_dibatalkan: number;
            /** Rincian Komoditas */
            rincian_komoditas?: components["schemas"]["RincianKomoditas"][];
            /** Catatan */
            catatan: string;
        };
        /**
         * Deteksi
         * @description One detected region, shaped like a YOLO detection.
         *
         *     `kotak` is [x_center, y_center, width, height], normalised 0-1 -- the
         *     Ultralytics `xywhn` convention, so the real model's output maps straight
         *     across with no rescaling.
         */
        Deteksi: {
            kelas: components["schemas"]["KondisiKode"];
            /** Keyakinan */
            keyakinan: number;
            /** Kotak */
            kotak: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HasilPencocokanResponse */
        HasilPencocokanResponse: {
            /** Id Penawaran */
            id_penawaran: string;
            komoditas: components["schemas"]["Komoditas"];
            /** Jumlah Cocok */
            jumlah_cocok: number;
            /** Pembeli */
            pembeli?: components["schemas"]["PembeliCocok"][];
            /** Pesan */
            pesan: string;
            /** Ringkasan Penyaringan */
            ringkasan_penyaringan?: {
                [key: string]: number;
            };
        };
        /**
         * JenisUsaha
         * @description PRD A-03: buyer business type.
         * @enum {string}
         */
        JenisUsaha: "pengolah_pangan" | "peternak" | "produsen_kompos" | "lainnya";
        /**
         * KartuBerbagi
         * @description PRD G-01: the shareable offer card, as data.
         *
         *     The React Native app renders this natively and passes the result to the
         *     OS share sheet (G-02). The backend deliberately does not render HTML or
         *     an image -- there is no web surface in this product (context.md).
         */
        KartuBerbagi: {
            /** Id Penawaran */
            id_penawaran: string;
            /** Judul */
            judul: string;
            /** Ringkasan */
            ringkasan: string;
            komoditas: components["schemas"]["Komoditas"];
            /** Volume Kg */
            volume_kg: number;
            /** Kondisi Terverifikasi */
            kondisi_terverifikasi: string;
            tingkat_keparahan: components["schemas"]["TingkatKeparahan"];
            metode_klasifikasi: components["schemas"]["MetodeKlasifikasi"];
            /** Label Verifikasi */
            label_verifikasi: string;
            /** Lokasi Umum */
            lokasi_umum: string;
            /** Mendesak */
            mendesak: boolean;
            /** Sisa Jendela Hari */
            sisa_jendela_hari?: number | null;
            /** Url Foto */
            url_foto?: string | null;
            /**
             * Tautan Dalam Aplikasi
             * @description Deep link kembali ke aplikasi (G-01).
             */
            tautan_dalam_aplikasi: string;
            /** Teks Siap Bagikan */
            teks_siap_bagikan: string;
        };
        /**
         * KecocokanTercatat
         * @description A stored match, as shown to a buyer in the reverse flow.
         */
        KecocokanTercatat: {
            /** Id Kecocokan */
            id_kecocokan: string;
            /** Id Penawaran */
            id_penawaran: string;
            /** Id Permintaan */
            id_permintaan: string | null;
            /**
             * Arah
             * @description 'maju' = petani mencari, 'balik' = permintaan tersentuh.
             */
            arah: string;
            /** Jarak Km */
            jarak_km: number;
            /** Skor Relevansi */
            skor_relevansi: number;
            /** Alasan */
            alasan: {
                [key: string]: unknown;
            };
            /** Waktu Dibuat */
            waktu_dibuat: string;
        };
        /**
         * KetersediaanPembeli
         * @description PRD C-03: does a buyer for this recommendation actually exist nearby?
         *
         *     Deliberately thin -- a count and the nearest distance, nothing about who.
         *     A recommendation only needs to say "yes, N buyers within X km can take
         *     this" or "no match found, informational only". The buyer list itself is
         *     the matching endpoint's job.
         */
        KetersediaanPembeli: {
            /**
             * Ada
             * @default false
             */
            ada: boolean;
            /**
             * Jumlah
             * @default 0
             */
            jumlah: number;
            /** Jarak Terdekat Km */
            jarak_terdekat_km?: number | null;
        };
        /**
         * KlasifikasiManualRequest
         * @description PRD B-07: the manual path a farmer can always fall back to.
         *
         *     The resulting listing is tagged `manual_dilaporkan_sendiri` and stays
         *     visibly distinguishable from CV-classified listings wherever a buyer sees
         *     it (PRD F-03).
         */
        KlasifikasiManualRequest: {
            komoditas: components["schemas"]["Komoditas"];
            pemicu: components["schemas"]["Pemicu"];
            /**
             * Jenis Kondisi
             * @example [
             *       "K2"
             *     ]
             */
            jenis_kondisi: components["schemas"]["KondisiKode"][];
            tingkat_keparahan: components["schemas"]["TingkatKeparahan"];
            /**
             * Citra
             * @description Opsional. Foto yang sudah diunggah sebelumnya, jika ada.
             */
            citra?: components["schemas"]["Citra"][];
            koordinat_ambil?: components["schemas"]["Koordinat"] | null;
        };
        /** KlasifikasiResponse */
        KlasifikasiResponse: {
            /** Id Klasifikasi */
            id_klasifikasi: string;
            komoditas: components["schemas"]["Komoditas"];
            pemicu: components["schemas"]["Pemicu"];
            /** Jenis Kondisi */
            jenis_kondisi: components["schemas"]["KondisiKode"][];
            tingkat_keparahan: components["schemas"]["TingkatKeparahan"];
            /**
             * Skor Keyakinan
             * @description Kosong untuk klasifikasi manual -- lihat metode_klasifikasi.
             */
            skor_keyakinan: number | null;
            metode_klasifikasi: components["schemas"]["MetodeKlasifikasi"];
            /** Label Bahasa */
            label_bahasa: string;
            /** Penjelasan */
            penjelasan: string;
            /** Butuh Konfirmasi Manual */
            butuh_konfirmasi_manual: boolean;
            /** Tindakan Disarankan */
            tindakan_disarankan: string;
            /** Deteksi */
            deteksi?: components["schemas"]["Deteksi"][];
            /** Citra */
            citra?: components["schemas"]["Citra"][];
            verifikasi: components["schemas"]["VerifikasiCitra"];
            /**
             * Sumber Placeholder
             * @description TRUE selama model YOLO belum terpasang dan hasil berasal dari pengklasifikasi tiruan. Lihat modules/classification/pengklasifikasi_mock.py.
             */
            sumber_placeholder: boolean;
        };
        /**
         * Komoditas
         * @description PRD B-03. `daun` is oversupply-only -- see `kombinasi_valid` below.
         * @enum {string}
         */
        Komoditas: "tomat" | "kentang" | "wortel" | "jagung" | "daun";
        /**
         * KondisiKode
         * @description PRD §11 condition taxonomy.
         * @enum {string}
         */
        KondisiKode: "K0" | "K1" | "K2" | "K3" | "K4" | "K5" | "K6";
        /**
         * KondisiPenyimpanan
         * @enum {string}
         */
        KondisiPenyimpanan: "terbuka" | "tertutup" | "berpendingin";
        /**
         * Koordinat
         * @description PRD §8 GeoPoint.
         */
        Koordinat: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** LaporanResponse */
        LaporanResponse: {
            /** Id Laporan */
            id_laporan: string;
            /** Id Transaksi */
            id_transaksi: string;
            /** Id Pelapor */
            id_pelapor: string;
            /** Id Terlapor */
            id_terlapor: string;
            /** Kondisi Diklaim */
            kondisi_diklaim: components["schemas"]["KondisiKode"][];
            /** Kondisi Ditemukan */
            kondisi_ditemukan: components["schemas"]["KondisiKode"][];
            /** Catatan */
            catatan?: string | null;
            /** Foto Pembanding */
            foto_pembanding?: components["schemas"]["Citra"][];
            status: components["schemas"]["StatusLaporan"];
            /** Waktu Dibuat */
            waktu_dibuat: string;
            /** Keterangan Dampak */
            keterangan_dampak: string;
        };
        /**
         * MetodeKlasifikasi
         * @description PRD B-07/F-03: self-reported listings stay visibly distinguishable.
         * @enum {string}
         */
        MetodeKlasifikasi: "otomatis" | "manual_dilaporkan_sendiri";
        /**
         * NilaiEstimasi
         * @description PRD C-02: estimated value range.
         *
         *     Produce value per kg. Never net-of-transport -- transport cost modelling
         *     is out of scope (PRD §3.2).
         */
        NilaiEstimasi: {
            /** Min */
            min: number;
            /** Max */
            max: number;
            /**
             * Satuan
             * @default Rp/kg
             */
            satuan: string;
        };
        /** NotifikasiResponse */
        NotifikasiResponse: {
            /** Id Notifikasi */
            id_notifikasi: string;
            /** Jenis */
            jenis: string;
            /** Judul */
            judul: string;
            /** Isi */
            isi: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Mendesak */
            mendesak: boolean;
            /**
             * Status Kirim
             * @description 'tercatat' selama pengiriman push masih placeholder -- notifikasi tersimpan dan dapat dibaca lewat API, tapi tidak dikirim ke perangkat. Lihat modules/notifications/pengirim.py.
             */
            status_kirim: string;
            /** Waktu Dibuat */
            waktu_dibuat: string;
            /** Waktu Dibaca */
            waktu_dibaca?: string | null;
        };
        /**
         * Opsi
         * @description One disposal/sale option (PRD C-02).
         */
        Opsi: {
            /** Nama */
            nama: string;
            /** Prioritas */
            prioritas: number;
            nilai_estimasi: components["schemas"]["NilaiEstimasi"];
            tingkat_upaya: components["schemas"]["TingkatUpaya"];
            /** Jenis Usaha Pembeli */
            jenis_usaha_pembeli?: components["schemas"]["JenisUsaha"][];
            /**
             * Butuh Kesegaran
             * @default false
             */
            butuh_kesegaran: boolean;
            /**
             * Catatan
             * @default
             */
            catatan: string;
        };
        /**
         * OpsiRekomendasi
         * @description One recommendation shown to a farmer (PRD C-02, C-03).
         */
        OpsiRekomendasi: {
            /** Nama */
            nama: string;
            nilai_estimasi: components["schemas"]["NilaiEstimasi"];
            tingkat_upaya: components["schemas"]["TingkatUpaya"];
            /** Catatan */
            catatan: string;
            /** Jenis Usaha Pembeli */
            jenis_usaha_pembeli?: components["schemas"]["JenisUsaha"][];
            ketersediaan_pembeli: components["schemas"]["KetersediaanPembeli"];
            /** Keterangan Pembeli */
            keterangan_pembeli: string;
            /** Id Aturan */
            id_aturan: string;
            /** Dasar Aturan */
            dasar_aturan: string;
            /** Penyesuaian */
            penyesuaian?: string | null;
        };
        /** PapanKomunitasResponse */
        PapanKomunitasResponse: {
            /** Wilayah */
            wilayah?: string | null;
            /** Penawaran Aktif */
            penawaran_aktif?: components["schemas"]["PenawaranRingkasPapan"][];
            /** Pos */
            pos?: components["schemas"]["PosKomunitas"][];
            /**
             * Catatan
             * @default Papan ini bersifat informasi dan koordinasi saja. Terra tidak menggabungkan pengiriman antar petani dan tidak menghitung biaya angkut (PRD G-04, §3.2).
             */
            catatan: string;
        };
        /**
         * PembeliCocok
         * @description One ranked buyer in the forward flow (PRD D-03 … D-06).
         */
        PembeliCocok: {
            /** Id Permintaan */
            id_permintaan: string;
            /** Id Pembeli */
            id_pembeli: string;
            /** Nama */
            nama: string;
            /** Nama Usaha */
            nama_usaha?: string | null;
            jenis_usaha: components["schemas"]["JenisUsaha"];
            /** Alamat Umum */
            alamat_umum?: string | null;
            /**
             * Jarak Km
             * @description Haversine, PRD D-01.
             */
            jarak_km: number;
            /** Skor Relevansi */
            skor_relevansi: number;
            /** Alasan */
            alasan: {
                [key: string]: unknown;
            };
            /** Volume Dibutuhkan */
            volume_dibutuhkan: number;
            /** Volume Minimum */
            volume_minimum: number;
            keparahan_maksimal: components["schemas"]["TingkatKeparahan"];
            rentang_harga: components["schemas"]["RentangHarga"];
            reputasi?: components["schemas"]["RingkasanReputasi"] | null;
            /** Tautan Whatsapp */
            tautan_whatsapp?: string | null;
        };
        /**
         * Pemicu
         * @description PRD B-04: what prompted the listing.
         * @enum {string}
         */
        Pemicu: "cacat_mutu" | "kelebihan_pasokan";
        /** PenawaranResponse */
        PenawaranResponse: {
            /** Id Penawaran */
            id_penawaran: string;
            /** Id Petani */
            id_petani: string;
            pemicu: components["schemas"]["Pemicu"];
            komoditas: components["schemas"]["Komoditas"];
            /** Jenis Kondisi */
            jenis_kondisi: components["schemas"]["KondisiKode"][];
            tingkat_keparahan: components["schemas"]["TingkatKeparahan"];
            /** Skor Keyakinan */
            skor_keyakinan: number | null;
            metode_klasifikasi: components["schemas"]["MetodeKlasifikasi"];
            /** Dilaporkan Sendiri */
            dilaporkan_sendiri: boolean;
            /** Volume */
            volume: number;
            /** Lama Sejak Panen */
            lama_sejak_panen?: number | null;
            kondisi_penyimpanan?: components["schemas"]["KondisiPenyimpanan"] | null;
            /**
             * Sisa Jendela Hari
             * @description Perkiraan sisa hari layak salur (H-02).
             */
            sisa_jendela_hari?: number | null;
            /** Mendesak */
            mendesak: boolean;
            /** Keterangan Jendela */
            keterangan_jendela: string;
            koordinat: components["schemas"]["Koordinat"];
            status: components["schemas"]["StatusPenawaran"];
            /** Citra */
            citra?: components["schemas"]["Citra"][];
            /**
             * Jumlah Permintaan Cocok
             * @default 0
             */
            jumlah_permintaan_cocok: number;
        };
        /**
         * PenawaranRingkasPapan
         * @description An active offer as it appears on the board -- coarse by design.
         */
        PenawaranRingkasPapan: {
            /** Id Penawaran */
            id_penawaran: string;
            komoditas: components["schemas"]["Komoditas"];
            /** Volume Kg */
            volume_kg: number;
            /** Kondisi */
            kondisi: string;
            /** Lokasi Umum */
            lokasi_umum: string;
            /** Mendesak */
            mendesak: boolean;
            /** Dilaporkan Sendiri */
            dilaporkan_sendiri: boolean;
        };
        /**
         * PendaftaranResponse
         * @description Registration also hands back the MVP access token.
         *
         *     Returning a credential in a response body is fine for this build and not
         *     for a real one -- see terra/core/security.py.
         */
        PendaftaranResponse: {
            /** Id Pengguna */
            id_pengguna: string;
            /** Nama */
            nama: string;
            peran: components["schemas"]["Peran"];
            koordinat: components["schemas"]["Koordinat"];
            /** Alamat Umum */
            alamat_umum?: string | null;
            /** Nomor Whatsapp */
            nomor_whatsapp?: string | null;
            /** Komoditas Utama */
            komoditas_utama?: components["schemas"]["Komoditas"][];
            jenis_usaha?: components["schemas"]["JenisUsaha"] | null;
            /** Nama Usaha */
            nama_usaha?: string | null;
            reputasi?: components["schemas"]["RingkasanReputasi"] | null;
            /** Token Akses */
            token_akses: string;
        };
        /**
         * Peran
         * @description PRD A-01: role chosen at signup.
         * @enum {string}
         */
        Peran: "petani" | "pembeli";
        /** PerbaruiLokasiRequest */
        PerbaruiLokasiRequest: {
            koordinat: components["schemas"]["Koordinat"];
            /** Alamat Umum */
            alamat_umum?: string | null;
        };
        /** PermintaanResponse */
        PermintaanResponse: {
            /** Id Permintaan */
            id_permintaan: string;
            /** Id Pembeli */
            id_pembeli: string;
            jenis_usaha: components["schemas"]["JenisUsaha"];
            /** Komoditas Dicari */
            komoditas_dicari: components["schemas"]["Komoditas"][];
            /** Kondisi Diterima */
            kondisi_diterima: components["schemas"]["KondisiKode"][];
            keparahan_maksimal: components["schemas"]["TingkatKeparahan"];
            /** Volume Minimum */
            volume_minimum: number;
            /** Volume Dibutuhkan */
            volume_dibutuhkan: number;
            /** Radius Maksimal */
            radius_maksimal: number;
            rentang_harga: components["schemas"]["RentangHarga"];
            koordinat: components["schemas"]["Koordinat"];
            status: components["schemas"]["StatusPermintaan"];
        };
        /** PosKomunitas */
        PosKomunitas: {
            /** Id Pos */
            id_pos: string;
            /** Id Penulis */
            id_penulis: string;
            /** Nama Penulis */
            nama_penulis?: string | null;
            /** Wilayah */
            wilayah: string;
            /** Isi */
            isi: string;
            /** Waktu Dibuat */
            waktu_dibuat: string;
        };
        /** ProfilResponse */
        ProfilResponse: {
            /** Id Pengguna */
            id_pengguna: string;
            /** Nama */
            nama: string;
            peran: components["schemas"]["Peran"];
            koordinat: components["schemas"]["Koordinat"];
            /** Alamat Umum */
            alamat_umum?: string | null;
            /** Nomor Whatsapp */
            nomor_whatsapp?: string | null;
            /** Komoditas Utama */
            komoditas_utama?: components["schemas"]["Komoditas"][];
            jenis_usaha?: components["schemas"]["JenisUsaha"] | null;
            /** Nama Usaha */
            nama_usaha?: string | null;
            reputasi?: components["schemas"]["RingkasanReputasi"] | null;
        };
        /** RekomendasiResponse */
        RekomendasiResponse: {
            /** Id Penawaran */
            id_penawaran: string;
            komoditas: components["schemas"]["Komoditas"];
            /** Jenis Kondisi */
            jenis_kondisi: components["schemas"]["KondisiKode"][];
            tingkat_keparahan: components["schemas"]["TingkatKeparahan"];
            /** Sisa Jendela Hari */
            sisa_jendela_hari?: number | null;
            /** Opsi */
            opsi?: components["schemas"]["OpsiRekomendasi"][];
            /** Catatan */
            catatan?: string | null;
            /** Versi Basis Aturan */
            versi_basis_aturan: number;
        };
        /**
         * RentangHarga
         * @description PRD E-01 `rentang_harga`.
         *
         *     The price a buyer offers per kg OF PRODUCE. Not a shipping rate, not a
         *     net-of-transport figure -- transport cost modelling is out of scope
         *     (PRD §3.2).
         */
        RentangHarga: {
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /**
             * Satuan
             * @default Rp/kg
             */
            satuan: string;
        };
        /** RincianKomoditas */
        RincianKomoditas: {
            komoditas: components["schemas"]["Komoditas"];
            /** Volume Kg */
            volume_kg: number;
            /** Nilai Rupiah */
            nilai_rupiah: number;
            /** Jumlah Transaksi */
            jumlah_transaksi: number;
        };
        /**
         * RingkasanKlasifikasi
         * @description What `classification` publishes to whoever turns a run into an offer.
         */
        RingkasanKlasifikasi: {
            /** Id Klasifikasi */
            id_klasifikasi: string;
            komoditas: components["schemas"]["Komoditas"];
            pemicu: components["schemas"]["Pemicu"];
            /** Jenis Kondisi */
            jenis_kondisi: components["schemas"]["KondisiKode"][];
            tingkat_keparahan: components["schemas"]["TingkatKeparahan"];
            /** Skor Keyakinan */
            skor_keyakinan: number;
            metode_klasifikasi: components["schemas"]["MetodeKlasifikasi"];
            /** Label Bahasa */
            label_bahasa: string;
            /** Butuh Konfirmasi Manual */
            butuh_konfirmasi_manual: boolean;
            /** Citra */
            citra?: components["schemas"]["Citra"][];
        };
        /**
         * RingkasanPengguna
         * @description What `onboarding` publishes about a user to other modules.
         */
        RingkasanPengguna: {
            /** Id Pengguna */
            id_pengguna: string;
            /** Nama */
            nama: string;
            peran: components["schemas"]["Peran"];
            koordinat: components["schemas"]["Koordinat"];
            /** Alamat Umum */
            alamat_umum?: string | null;
            /** Nomor Whatsapp */
            nomor_whatsapp?: string | null;
            jenis_usaha?: components["schemas"]["JenisUsaha"] | null;
            /** Nama Usaha */
            nama_usaha?: string | null;
            /** Komoditas Utama */
            komoditas_utama?: components["schemas"]["Komoditas"][];
        };
        /**
         * RingkasanReputasi
         * @description What `trust` publishes about a user (PRD F-05, F-06, F-07, D-05).
         */
        RingkasanReputasi: {
            /** Id Pengguna */
            id_pengguna: string;
            peran: components["schemas"]["Peran"];
            /**
             * Jumlah Transaksi
             * @default 0
             */
            jumlah_transaksi: number;
            /** Skor Rata Rata */
            skor_rata_rata?: number | null;
            /**
             * Jumlah Laporan Ketidaksesuaian
             * @default 0
             */
            jumlah_laporan_ketidaksesuaian: number;
            /**
             * Jumlah Pembatalan Sepihak
             * @default 0
             */
            jumlah_pembatalan_sepihak: number;
            /** Tingkat Akurasi Deskripsi */
            tingkat_akurasi_deskripsi?: number | null;
            /**
             * Ringkasan Teks
             * @default Belum ada riwayat transaksi
             */
            ringkasan_teks: string;
        };
        /**
         * RingkasanTransaksi
         * @description What `trust` publishes about a completed deal (dashboard reads these).
         */
        RingkasanTransaksi: {
            /** Id Transaksi */
            id_transaksi: string;
            /** Id Penawaran */
            id_penawaran: string | null;
            /** Id Petani */
            id_petani: string;
            /** Id Pembeli */
            id_pembeli: string;
            komoditas: components["schemas"]["Komoditas"];
            /** Volume */
            volume: number;
            /** Nilai Total */
            nilai_total: number;
            status: components["schemas"]["StatusTransaksi"];
            /** Waktu Selesai */
            waktu_selesai?: string | null;
        };
        /**
         * SelesaikanTransaksiRequest
         * @description PRD §10.1 step 8: both parties rate each other.
         */
        SelesaikanTransaksiRequest: {
            /** Rating Untuk Petani */
            rating_untuk_petani?: number | null;
            /** Rating Untuk Pembeli */
            rating_untuk_pembeli?: number | null;
            /**
             * Nilai Total
             * @description Koreksi nilai akhir bila berbeda dari kesepakatan.
             */
            nilai_total?: number | null;
        };
        /**
         * StatusLaporan
         * @enum {string}
         */
        StatusLaporan: "menunggu" | "terkonfirmasi" | "ditolak";
        /**
         * StatusPenawaran
         * @enum {string}
         */
        StatusPenawaran: "baru" | "dicocokkan" | "tersalurkan" | "kedaluwarsa";
        /**
         * StatusPermintaan
         * @enum {string}
         */
        StatusPermintaan: "aktif" | "terpenuhi" | "kedaluwarsa";
        /**
         * StatusTransaksi
         * @enum {string}
         */
        StatusTransaksi: "disepakati" | "selesai" | "dibatalkan_pembeli" | "dibatalkan_petani";
        /**
         * TingkatKeparahan
         * @enum {string}
         */
        TingkatKeparahan: "tidak_ada" | "ringan" | "sedang" | "berat";
        /**
         * TingkatUpaya
         * @description PRD C-02: how much work a recommendation asks of the farmer.
         * @enum {string}
         */
        TingkatUpaya: "rendah" | "sedang" | "tinggi";
        /** TinjauLaporanRequest */
        TinjauLaporanRequest: {
            /** @description terkonfirmasi atau ditolak. Hanya laporan terkonfirmasi yang memengaruhi skor. */
            status: components["schemas"]["StatusLaporan"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerifikasiCitra
         * @description Trust signals attached to a classification (PRD F-01, F-02).
         *
         *     Server-side verification can only go so far: the backend cannot prove a
         *     photo came from the in-app camera rather than the gallery. What it can do
         *     is check that the capture metadata PRD B-02 requires is actually present,
         *     and compare the geotag against the farmer's registered location. Both
         *     outcomes are reported, never silently swallowed.
         */
        VerifikasiCitra: {
            /**
             * Metadata Lengkap
             * @description Waktu ambil dan koordinat tersedia untuk setiap foto (B-02).
             */
            metadata_lengkap: boolean;
            /**
             * Geotag Mencurigakan
             * @description Geotag jauh dari lokasi terdaftar petani (F-02). Ditandai untuk ditinjau, bukan ditolak.
             */
            geotag_mencurigakan: boolean;
            /** Jarak Dari Lokasi Terdaftar Km */
            jarak_dari_lokasi_terdaftar_km?: number | null;
            /** Catatan */
            catatan: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    daftar_petani_onboarding_petani_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DaftarPetaniRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendaftaranResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_pembeli_terdaftar_onboarding_pembeli_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RingkasanPengguna"][];
                };
            };
        };
    };
    daftar_pembeli_onboarding_pembeli_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DaftarPembeliRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendaftaranResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profil_saya_onboarding_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilResponse"];
                };
            };
        };
    };
    perbarui_lokasi_onboarding_saya_lokasi_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerbaruiLokasiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profil_pengguna_onboarding_pengguna__id_pengguna__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_pengguna: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    klasifikasi_otomatis_klasifikasi_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_klasifikasi_otomatis_klasifikasi_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KlasifikasiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    klasifikasi_manual_klasifikasi_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KlasifikasiManualRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KlasifikasiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ambil_klasifikasi_klasifikasi__id_klasifikasi__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_klasifikasi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RingkasanKlasifikasi"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_penawaran_penawaran_get: {
        parameters: {
            query?: {
                komoditas?: components["schemas"]["Komoditas"] | null;
                status_penawaran?: components["schemas"]["StatusPenawaran"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenawaranResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buat_penawaran_penawaran_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuatPenawaranRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenawaranResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    penawaran_saya_penawaran_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenawaranResponse"][];
                };
            };
        };
    };
    detail_penawaran_penawaran__id_penawaran__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_penawaran: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenawaranResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tandai_tersalurkan_penawaran__id_penawaran__tersalurkan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_penawaran: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenawaranResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buat_permintaan_permintaan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuatPermintaanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermintaanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    permintaan_saya_permintaan_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermintaanResponse"][];
                };
            };
        };
    };
    tutup_permintaan_permintaan__id_permintaan__tutup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_permintaan: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermintaanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rekomendasi_penawaran__id_penawaran__rekomendasi_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_penawaran: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RekomendasiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    basis_aturan_basis_aturan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasisPengetahuan"];
                };
            };
        };
    };
    cari_pembeli_penawaran__id_penawaran__pembeli_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_penawaran: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HasilPencocokanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kecocokan_penawaran_penawaran__id_penawaran__kecocokan_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_penawaran: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KecocokanTercatat"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kecocokan_saya_kecocokan_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KecocokanTercatat"][];
                };
            };
        };
    };
    buat_transaksi_transaksi_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuatTransaksiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RingkasanTransaksi"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    selesaikan_transaksi_transaksi__id_transaksi__selesai_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_transaksi: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelesaikanTransaksiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RingkasanTransaksi"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batalkan_transaksi_transaksi__id_transaksi__batal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_transaksi: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatalkanTransaksiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RingkasanTransaksi"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transaksi_saya_transaksi_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RingkasanTransaksi"][];
                };
            };
        };
    };
    buat_laporan_laporan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuatLaporanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaporanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tinjau_laporan_laporan__id_laporan__tinjau_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_laporan: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TinjauLaporanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaporanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    laporan_terhadap_laporan_terhadap__id_pengguna__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_pengguna: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaporanResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reputasi_reputasi__id_pengguna__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_pengguna: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RingkasanReputasi"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notifikasi_saya_notifikasi_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifikasiResponse"][];
                };
            };
        };
    };
    tandai_dibaca_notifikasi__id_notifikasi__dibaca_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_notifikasi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifikasiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kartu_penawaran_penawaran__id_penawaran__kartu_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_penawaran: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KartuBerbagi"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catat_berbagi_penawaran__id_penawaran__kartu_dibagikan_post: {
        parameters: {
            query?: {
                kanal?: string;
            };
            header?: never;
            path: {
                id_penawaran: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    papan_komunitas_papan_get: {
        parameters: {
            query?: {
                wilayah?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PapanKomunitasResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buat_pos_komunitas_pos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuatPosRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosKomunitas"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dampak_saya_dampak_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DampakResponse"];
                };
            };
        };
    };
    akar__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    kesehatan_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
